import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Bryan Vera page',
	description: 'Generated by create next app',
	openGraph: {
		title: 'Bryan Vera page',
		description: 'Generated by create next app',
		url: 'https://tu-dominio.com', // Reemplaza con la URL de tu página
		images: [
			{
				url: './images/imagen.png', // Ruta a tu imagen
				alt: 'Imagen de Bryan Vera',
				width: 1200, // Ancho de la imagen (opcional)
				height: 600, // Alto de la imagen (opcional)
			},
		],
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
